# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tachiyomi.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ftachiyomi.proto\x12\ttachiyomi\"\x9a\x01\n\x06\x42\x61\x63kup\x12+\n\x0b\x62\x61\x63kupManga\x18\x01 \x03(\x0b\x32\x16.tachiyomi.BackupManga\x12\x33\n\x10\x62\x61\x63kupCategories\x18\x02 \x03(\x0b\x32\x19.tachiyomi.BackupCategory\x12.\n\rbackupSources\x18\x65 \x03(\x0b\x32\x17.tachiyomi.BackupSource\"\xb1\x02\n\x0b\x42\x61\x63kupManga\x12\x0e\n\x06source\x18\x01 \x01(\x03\x12\x0b\n\x03url\x18\x02 \x01(\t\x12\r\n\x05title\x18\x03 \x01(\t\x12\x0e\n\x06\x61rtist\x18\x04 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x05 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x06 \x01(\t\x12\r\n\x05genre\x18\x07 \x03(\t\x12\x0e\n\x06status\x18\x08 \x01(\x05\x12\x14\n\x0cthumbnailUrl\x18\t \x01(\t\x12\x11\n\tdateAdded\x18\r \x01(\x03\x12\x0e\n\x06viewer\x18\x0e \x01(\x05\x12*\n\x08\x63hapters\x18\x10 \x03(\x0b\x32\x18.tachiyomi.BackupChapter\x12\x12\n\ncategories\x18\x11 \x03(\x05\x12)\n\x07history\x18\x17 \x03(\x0b\x32\x18.tachiyomi.BackupHistory\"\xc6\x01\n\rBackupChapter\x12\x0b\n\x03url\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x11\n\tscanlator\x18\x03 \x01(\t\x12\x0c\n\x04read\x18\x04 \x01(\x08\x12\x10\n\x08\x62ookmark\x18\x05 \x01(\x05\x12\x14\n\x0clastPageRead\x18\x06 \x01(\x03\x12\x11\n\tdateFetch\x18\x07 \x01(\x03\x12\x12\n\ndateUpload\x18\x08 \x01(\x03\x12\x15\n\rchapterNumber\x18\t \x01(\x02\x12\x13\n\x0bsourceOrder\x18\n \x01(\x03\"<\n\x0e\x42\x61\x63kupCategory\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05order\x18\x02 \x01(\x05\x12\r\n\x05\x66lags\x18\x03 \x01(\x05\".\n\x0c\x42\x61\x63kupSource\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08sourceId\x18\x02 \x01(\x03\"D\n\rBackupHistory\x12\x0b\n\x03url\x18\x01 \x01(\t\x12\x10\n\x08lastRead\x18\x02 \x01(\x03\x12\x14\n\x0creadDuration\x18\x03 \x01(\x03\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tachiyomi_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BACKUP._serialized_start=31
  _BACKUP._serialized_end=185
  _BACKUPMANGA._serialized_start=188
  _BACKUPMANGA._serialized_end=493
  _BACKUPCHAPTER._serialized_start=496
  _BACKUPCHAPTER._serialized_end=694
  _BACKUPCATEGORY._serialized_start=696
  _BACKUPCATEGORY._serialized_end=756
  _BACKUPSOURCE._serialized_start=758
  _BACKUPSOURCE._serialized_end=804
  _BACKUPHISTORY._serialized_start=806
  _BACKUPHISTORY._serialized_end=874
# @@protoc_insertion_point(module_scope)
